limit_req_zone  $binary_remote_addr  zone=api_limit:10m  rate=30r/m;
limit_conn_zone $binary_remote_addr  zone=conn_limit:10m;

map $request_method $write_limit_key {
    POST    $binary_remote_addr;
    PUT     $binary_remote_addr;
    DELETE  $binary_remote_addr;
    default "";
}
limit_req_zone $write_limit_key zone=write_limit:10m rate=5r/m;

limit_req_status  429;
limit_conn_status 429;
