FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    libgmp-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install gmp pdo_pgsql

WORKDIR /app

# standby mode
CMD ["tail", "-f", "/dev/null"]